---
title: "Chart Generator 2"
author: "ECO"
output: 
  md_document:
    variant: markdown_github
#   rmarkdown::html_vignette:
    fig_width: 7.5
    fig_height: 4.5
# vignette: >
#   %\VignetteIndexEntry{Chart Generator 2}
#   %\VignetteEngine{knitr::rmarkdown}
#   %\VignetteEncoding{UTF-8}
---

## Chart Generator 2

### ECO

```{r knitr, echo=FALSE}
library("knitr")
knitr::opts_chunk$set(
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    fig.align = 'center',
    fig.pos = 'H',
    fig.path = "plots/",
    ## dev = c("png", "svg"),
    dev = "svg"
   ## ,
    ## dpi = 500
)
```


```{r init}
## source("../lib/EcoChartGenerator_libraries.R")

library(ggthemes)
library(ggplot2)
library(readxl)
library(zoo)
library(stats)
library(plyr)
library(dplyr)
library(tidyr)
library(xts)
library(reshape2)
library(rvg)
library(stringr)
library(extrafont)
library(lubridate)

library(grid)
library(gridExtra)
library(devEMF)

## - StopProgramIfLibraryIsMissing
## - theme_ECO
## - manage_axis
source("../lib/ECO_ggplot_theme.r")

## - read_eo_sheet
## - clean_df
## - eco_format_ggplot
source("../lib/helper.R")

```


```{r param}
param <- yaml::yaml.load_file("../demo-2/param.yml")
lang <- "EN"

param_labelY <- manage_axis_title(param$labelY, param$YPosition)

## ported from ../lib/ECO_ggplot_theme.r
eco_default <- yaml::yaml.load_file("../inst/extdata/eco_default.yml")

```


```{r data}
sheets <- c("A", "Q", "M", "D")
## dat_empty <- data.frame(Date = "1900-01-01")

DATA <- lapply(sheets,
               function(x) read_eo_sheet(sheet = paste0("DATA_", x),
                                         file = "../data-raw/_TEST_CHN_DEF.xlsx"
                                        ## ,
                                        ##  dat_empty = dat_empty
                                         ))
names(DATA) <- sheets

prz_data_a  <- prz_data_q <- prz_data_m <- data.frame(NULL)


## Merge A/Q/M/D data in one data.frame
data <- Eco_Merge_AQMD_DataFrames(
  param$chart_type,
  ## xls_data_a,
  ## xls_data_q,
  ## xls_data_m,
  ## xls_data_d,
  DATA$A,
  DATA$Q,
  DATA$M,
  DATA$D,
  prz_data_a,
  prz_data_q,
  prz_data_m
)

```


```{r chart}
## Define xTicks labels, minor/major ticks
xTicks <- Eco_GetXTicks(param_y_min = param$y_min,
                        param_y_max = param$y_max,
                        dates = data$Date,
                        year = param$x_break)

## manual addition
xTicks$XTICKS_LABELS[5] <- "2017-01-01"


## Bar/Stacked Bar preparation
stackedbar_order <- tribble(
  ~cSeries, ~cOrder,
  "Goods trade", "1",
  "Service trade", "2",
  "Primary income", "3",
  "Secondary income", "4")


## You can change order in stacked-bar here (in the column cGroupOrder)
stackedbar_group_order <- tribble(
  ~cSeries, ~cGroupOrder,
  "Goods trade", "4",
  "Service trade", "3",
  "Primary income", "2",
  "Secondary income", "1")

stackedbar_data <- na.omit(melt(data[,c("Date","Goods trade","Service trade","Primary income","Secondary income")],id=c("Date")))
stackedbar_data$variable <- as.character(stackedbar_data$variable)
stackedbar_data <- inner_join(x = stackedbar_data,
                              y = stackedbar_order,
                              by = c("variable"="cSeries"))
stackedbar_data <- inner_join(x = stackedbar_data,
                              y = stackedbar_group_order,
                              by = c("variable"="cSeries"))

if (interactive()==TRUE) { graphics.off() }

my_chart <- ggplot(data = data) +
  expand_limits(y = c(param$y_min, param$y_max)) +
  ## Series "Goods trade","Service trade","Primary income","Secondary income" (Stacked-bar)
  geom_bar(data = stackedbar_data,
           mapping = aes(x = Date,
                         y = value,
                         fill = cOrder,
                         group = cGroupOrder),
           stat = "identity",
           position = "stack",
           color = "black",
           size = 0.3) +
                                        # Series 5: Current balance (Color=black, Geom=line, Line type=solid)
  geom_line(data = na.omit(data[,c("Date", "Current balance")]),
            mapping = aes(x = Date,
                          y = `Current balance`,
                          color = "5"),
            size = eco_default$line_width,
            linetype = "solid") +
  ## Set series colors
  scale_color_manual(labels = c("5" = param[[lang]]$series_labels[5]),
                     values = c("5" = eco_default$color_values[11])) +
  scale_fill_manual(labels = c("1" = param[[lang]]$series_labels[1],
                               "2" = param[[lang]]$series_labels[2],
                               "3" = param[[lang]]$series_labels[3],
                               "4" = param[[lang]]$series_labels[4]),
                    values = c("1" = eco_default$color_values[1],
                               "2" = eco_default$color_values[4],
                               "3" = eco_default$color_values[3],
                               "4" = eco_default$color_values[8])) +
  ## Reference Line (horizontal)
  geom_hline(yintercept =  c(0),
             color = "black",
             linetype = "solid") +
  ## Set X ticks
  scale_x_date(breaks = xTicks$XTICKS_LABELS,
               date_labels = "%Y",
               expand = c(0,0)) +
  ## Set Y ticks
  scale_y_continuous(position = param$YPosition,
                     breaks = seq(from = param$y_min,
                                  to = param$y_max,
                                  by = param$y_break),
                     expand = c(0, 0)) +
  ## Add title, subtiles, x/y labels
  labs(x = "",
       y = param_labelY,
       title = param[[lang]]$title,
       subtitle = param[[lang]]$subtitle) +
  ## The 0.001 fix a bug on double axis display (for "DEU Labour market")
  coord_cartesian(ylim = c(param$y_min - 0.001 * abs(param$y_min), param$y_max)) +
  ## Apply ECO theme
  theme_ECO(legendposition = c(param[[lang]]$legendX, param[[lang]]$legendY),
            legenddirection = param[[lang]]$legendDir,
            panelontop = param$panel_ontop,
            rotateXLabel = "NO",
            ticksOnX = "YES") +
  xTicks$XTICKS_MINOR() +
  xTicks$XTICKS_MAJOR()

```


```{r plot}
print(my_chart)

```
